name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
tag-prefix: 'v'
# prerelease: true
prerelease-identifier: 'pre'
# latest: false
categories:
    - title: Breaking Changes ⚠
      label: 'breaking-change'
    - title: Exciting New Features 🚀
      label: 'feature'
    - title: Bug Fixing 🐞
      label: 'fix'
    - title: Miscellaneous 🛠
      labels:
          - 'chore'
          # - 'documentation'
          # - 'refactor'
          # - 'dependencies'
          # - 'ci'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
    major:
        labels:
            - 'major'
    minor:
        labels:
            - 'minor'
    patch:
        labels:
            - 'patch'
    default: patch
header: |
    # What's Changed

footer: |

    **Full Changelog:** [$PREVIOUS_TAG...v$RESOLVED_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)
template: |
    $CHANGES
autolabeler:
    - label: 'chore'
      branch:
          - '/^chore[^/]*\/.+/'
    # - label: 'ci'
    #   branch:
    #       - '/^ci[^/]*\/.+/'
    - label: 'fix'
      branch:
          - '/^fix[^/]*\/.+/'
    - label: 'feature'
      branch:
          - '/^feat[^/]*\/.+/'
    - label: 'minor'
      branch:
          - '/^feat[^/]*\/.+/'
    # - label: 'refactor'
    #   branch:
    #       - '/^refactor[^/]*\/.+/'
    # - label: 'documentation'
    #   branch:
    #       - '/^doc[^/]*\/.+/'