name: Autolabeler

on:
    # Trigger the workflow on pull request to autolabelize Pull Requests
    # Will not update the draft, only the PR labels
    pull_request:
        types: [opened, reopened, synchronize]
        branches-ignore:
            - 'renovate/**'

permissions:
    contents: read

jobs:
    update_release_draft:
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: release-drafter/release-drafter@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}