# This action runs when a Pull Request is opened or synchronized
# Goal is to run release-drafter to automatically assign the right labels
name: ReleaseDrafter/Autolabeler

on:
    # Trigger the workflow on pull request to autolabelize Pull Requests
    # Will not update the draft, only the PR labels
    pull_request:
        types: [opened, reopened, synchronize]
        branches-ignore:
            - 'renovate/**'

permissions:
    contents: read

jobs:
    assign-labels:
      - name: Assign labels on PR
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: release-drafter/release-drafter@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}