# This action runs when a Repository Dispatch is detected (triggered FROM CircleCI)
# Goal is to run release-drafter action to create a RELEASE (a final one)
# And run the CircleCI pipeline de build & deploy in live the RELEASE
name: ReleaseDrafter/Release

on:
    repository_dispatch:
        types: [pre_release_approved]

permissions:
    contents: read

jobs:
    publish-stable-release:
        name: Create & publish Release
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        # This job exposes the output of release-drafter: the generated tag_name
        outputs:
          tag_name: ${{ steps.release-drafter.outputs.tag_name }}
        steps:
            - id: release-drafter
              uses: release-drafter/release-drafter@v5
              with:
                commitish: main
                # Create a final release
                prerelease: false
                # Do not put it in draft, publish it directly
                publish: true
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    trigger-circleci:
        # Important: Release must be created prior running this action
        needs: publish-stable-release
        name: Trigger CircleCI for Release
        runs-on: ubuntu-latest
        steps:
            - id: release
              uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
              with:
                # Provide the tag_name generated by the previous job (indirectly release-drafter)
                GHA_Meta: ${{ needs.publish-stable-release.outputs.tag_name }}
              env:
                CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
            - run: echo ${{needs.publish-stable-release.outputs.tag_name}}