# This action runs when a Repository Dispatch is detected (trigger FROM CircleCI)
# Goal is to run release-drafter action to create a RELEASE (a final one)
name: ReleaseDrafter/Release

on:
    repository_dispatch:
        types: [pre_release_approved]

permissions:
    contents: read

jobs:
    update_release_draft:
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: release-drafter/release-drafter@v5
              with:
                  commitish: main
                  prerelease: false
                #   disable-autolabeler: true #My bad, was not necessary
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}