# This action runs when a Repository Dispatch is detected (trigger FROM CircleCI)
# Goal is to run release-drafter action to create a RELEASE (a final one)
# And run the CircleCI pipeline de build & deploy in live the RELEASE
name: ReleaseDrafter/Release

on:
    repository_dispatch:
        types: [pre_release_approved]

permissions:
    contents: read

jobs:
    update-release-draft:
        name: Create & publish Release
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            uses: release-drafter/release-drafter@v5
            with:
                commitish: main
                prerelease: false
                publish: true
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    trigger-circleci:
        name: Trigger CircleCI for Release
        runs-on: ubuntu-latest
        steps:
            id: release
            uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
            need: update-release-draft
            with:
                GHA_Meta: 'final-release'
            env:
                CCI_TOKEN: ${{ secrets.CCI_TOKEN }}