name: CircleCI Trigger PR Checks

on:
    pull_request:
        types: [opened, synchronize]
jobs:
    trigger-circleci:
        runs-on: ubuntu-latest
        steps:
            - name: PullRequest
              id: pr
              uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
              env:
                  CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
