# This action runs when a Pull Request is opened or synchronized
# Goal is to trigger CircleCI pipeline to run quality check & deploy on ephemeral env
name: CircleCITrigger/PullRequest

on:
    pull_request:
        types: [opened, synchronize]
jobs:
    trigger-circleci:
        name: Triggler CircleCI pipeline for Pull Request
        runs-on: ubuntu-latest
        steps:
            - id: pr
              uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
              env:
                  CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
