# This action runs when a a pre-release is published from Github.
# Since stable release is created through github action this action should never be triggered manually by a stable release.
# BUT "in case of", this action is filtered to only handle "prerelease" event to prevent any misusage.
# Goal is to trigger CircleCI pipeline to build & deploy on PREVIEW
name: CircleCITrigger/PreRelease

on:
    release:
        types: [published]
jobs:
    trigger-circleci:
        name: Triggler CircleCI pipeline for Pre-Release
        if: "github.event.release.prerelease"
        runs-on: ubuntu-latest
        steps:
            - id: pre-release
              uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
              env:
                CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
