# This action runs when a merge on main is detected
# Goal is to run release-drafter action to create a PRE-RELEASE
name: ReleaseDrafter/PreRelease

on:
    # Trigger the workflow on merge on main to create / update the release draft
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    update-pre-release-draft:
        name: Update Pre-Release draft
        permissions:
            contents: write
            pull-requests: read
        runs-on: ubuntu-latest
        steps:
              uses: release-drafter/release-drafter@v5
              with:
                  commitish: main
                  prerelease: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}