# This action runs when a a release (pre-release or final release) is published from Github
# BUT, is filtered to only handle "prerelease"
# Goal is to trigger CircleCI pipeline to build & deploy on PREVIEW
name: CircleCITrigger/PreRelease

on:
    release:
        types: [published]
jobs:
    trigger-circleci:
        if: "github.event.release.prerelease"
        runs-on: ubuntu-latest
        steps:
            - name: Release
              id: release
              uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
              with:
                  GHA_Meta: 'pre-release'
              env:
                  CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
